version: 2


jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git

    steps:
      - run: apk add --no-cache bash curl

      - checkout
      - setup_remote_docker

      - run: docker build -t stevenmburns/tally_image .

      - run: docker run --name test-container stevenmburns/tally_image bash -c "source /general/bin/activate && mkdir -p /test-reports && pytest --junitxml=test-reports/junit.xml -- /general/lib/python3.6/site-packages/tally/tally.py"

      - run: mkdir -p test-reports/pytest && docker cp test-container:/test-reports/junit.xml test-reports/pytest

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - run: |
          ci_env=`curl -s https://codecov.io/env | bash`
          echo "ci_env: $ci_env"
          docker run -e CODACY_PROJECT_TOKEN $ci_env --name coverage-container stevenmburns/tally_image bash -c "source /general/bin/activate && pytest --cov=tally -rs -- /general/lib/python3.6/site-packages/tally/tally.py && coverage html && coverage-badge -o htmlcov/coverage.svg && coverage xml && bash <(curl -s https://codecov.io/bash) && python-codacy-coverage -r coverage.xml"

      - run: mkdir -p coverage-reports && docker cp coverage-container:/htmlcov coverage-reports/

      - store_artifacts:
          path: coverage-reports
