version: 2


jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git

    steps:
      - run: apk add --no-cache bash curl

      - checkout
      - setup_remote_docker

      - run: |
          docker build -t stevenmburns/tally_image .
          docker run --mount source=testVol,target=--name tally-container stevenmburns/tally_image bash -c "source /general/bin/activate && cd tally && coverage run --source=tally,tests setup.py test && coverage html && coverage-badge -o htmlcov/coverage.svg && coverage xml"
          mkdir -p test-reports/tally && docker cp tally-container:/tally/junit.xml test-reports/tally
          mkdir -p coverage-reports/tally && docker cp tally-container:/tally/htmlcov coverage-reports/tally && docker cp tally-container:/tally/coverage.xml coverage-reports/tally

      - run: |
          docker build -f Dockerfile.sgi -t stevenmburns/sgi_image .
          docker run --name sgi-container stevenmburns/sgi_image bash -c "source /general/bin/activate && cd sgi && coverage run --source=sgi,tests setup.py test && coverage html && coverage-badge -o htmlcov/coverage.svg && coverage xml"
          mkdir -p test-reports/sgi && docker cp sgi-container:/sgi/junit.xml test-reports/sgi
          mkdir -p coverage-reports/sgi && docker cp sgi-container:/sgi/htmlcov coverage-reports/sgi && docker cp sgi-container:/sgi/coverage.xml coverage-reports/sgi

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: coverage-reports

      - run: |
          (cd coverage-reports && tar cvf - .) | docker run --mount source=coverageVol,target=/coverage-reports -i ubuntu bash -c "cd coverage-reports && tar xvf -"
          ci_env=`curl -s https://codecov.io/env | bash`
          docker run -e CODACY_PROJECT_TOKEN $ci_env --name coverage-container --mount source=coverageVol,target=/coverage-reports stevenmburns/sgi_image bash -c "source /general/bin/activate &&  bash <(curl -s https://codecov.io/bash) && python-codacy-coverage -r coverage-reports/tally/coverage.xml -r coverage-reports/sgi/coverage.xml"
