version: 2


jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git

    steps:
      - run: apk add --no-cache bash curl

      - checkout
      - setup_remote_docker

      - run: |
          docker build -t stevenmburns/tally_image .
          docker run --mount source=testVol,target=/test-reports --mount source=coverageVol,target=/coverage-reports stevenmburns/tally_image bash -c "source /general/bin/activate && cd tally && coverage run --source=tally,tests setup.py test && coverage html && coverage-badge -o htmlcov/coverage.svg && mkdir /test-reports/tally && cp /tally/junit.xml /test-reports/tally && mkdir /coverage-reports/tally && cp -r /tally/.coverage /tally/htmlcov /coverage-reports/tally"

      - run: |
          docker build -f Dockerfile.sgi -t stevenmburns/sgi_image .
          docker run --mount source=testVol,target=/test-reports --mount source=coverageVol,target=/coverage-reports stevenmburns/sgi_image bash -c "source /general/bin/activate && cd sgi && coverage run --source=sgi,tests setup.py test && coverage html && coverage-badge -o htmlcov/coverage.svg && mkdir /test-reports/sgi && cp /sgi/junit.xml /test-reports/sgi && mkdir /coverage-reports/sgi && cp -r /sgi/.coverage /sgi/htmlcov /coverage-reports/sgi"

      - run: |
          docker run -e CODACY_PROJECT_TOKEN -e CIRCLE_SHA1 --name coverage-container --mount source=coverageVol,target=/coverage-reports stevenmburns/sgi_image bash -c "source /general/bin/activate && cd coverage-reports && coverage combine sgi/.coverage tally/.coverage && cd .. && cd coverage-reports && coverage xml && cd .. && python-codacy-coverage -r coverage-reports/coverage.xml -c $CIRCLE_SHA1 -d /"

      - run: docker run --mount source=testVol,target=/test-reports --mount source=coverageVol,target=/coverage-reports ubuntu bash -c "tar cvf - coverage-reports test-reports" | tar xvf -

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: coverage-reports
